const mongoose = require("mongoose");
const Schema   = mongoose.Schema;
ObjectId       = Schema.ObjectId; 

const dataSchema = new mongoose.Schema({ 
    name: { type: String, required: true },
    slug: { type: String, required: true },
    status:{ type: Boolean, default: false },
    is_approved: { type: Boolean, default: false },
    image: { type: String},
    product_type: { type: String, required: true},
    product_gallery: [{type: String,dafault:[],required: true}],
    product_description: { type: String, required: true },
    product_count: { type: Number, default: 100},
    product_availability: { type: String, required: true }, 
    product_discount: { type: Number},
    pay_on_delivery: { type: Boolean, default: false },
    regular_price: { type: Number, required: true },
    replacement_policy: { type: Boolean, default: false },
    sale_price: { type: Number},
    category : {type: ObjectId, required: true},
    sub_category : {type: ObjectId, required: true},
    related_products: [],
    
    brand: { type: ObjectId, required: true },
    series: { type: String, required: false },
    model_number: { type: String, required: false },
    manufacturer: { type: String, required: false },
    package: { type: String, required: false },
    dimensions: { type: String, required: false },
    ram_size: { type: String, required: false },
    country_of_origin: { type: String, required: false },
    item_weight: { type: String, required: false },
    memory_technology: { type: String, required: false },
    clock_speed: { type: String, required: false },
    screen_display_size: { type: String, required: false },
    screen_resolution: { type: String, required: false },
    processor: { type: String, required: false },
    graphics_coprocessor: { type: String, required: false },
    hard_drive: { type: String, required: false },
    chipset_brand: { type: String, required: false },
    card_description: { type: String, required: false },
    operating_system: { type: String, required: false },
    processor_brand: { type: String, required: false },
    processor_count: { type: String, required: false },
    flash_memory_size: { type: String, required: false },
    memory_speed: { type: String, required: false },
    wireless_type: { type: String, required: false },
    batteries: { type: String, required: false },
    power_source: { type: String, required: false },
    color: { type: String, required: false },
    connection_type: { type: String, required: false },
    model_name: { type: String, required: false },
    part_number: { type: String, required: false },
    compatible_devices: { type: String, required: false },

    nexait_delivery: { type: Boolean, default: false },
    virtual_id: { type: String, required: false }, 
    art_by: {type: ObjectId, required: true},
    meta_description : { type: String, required: true },
    meta_title: { type: String, required: true },
    meta_tags : { type: String, required: true },
    created_at: {type: Date,required: true,default: Date.now,},
    updated_at: {type: Date,required: true,default: Date.now,},
    isDeleted: { type: Boolean, default: false },
       
});  

module.exports = mongoose.model("product", dataSchema);